from .config.cors import *
from .config.databases import *
from .config.installed_apps import *
from .config.localization import *
from .config.main import *
from .config.media import *
from .config.middlewares import *
from .config.migrations_structure import *
from .config.password_criteria import *
from .config.rest_framework import *
from .config.templates import *
